# This is a generated file. Not intended for manual editing.
services:
  eportfolio.api:
    build:
      context: "/home/ianerglitch/Documents/ePortfolioContainers/ePortfolioContainersBackEnd"
      dockerfile: "src/Presentation/ePortfolio.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/ePortfolio.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "eportfolioapi:dev"
    ports: []
    volumes:
    - "/home/ianerglitch/Documents/ePortfolioContainers/ePortfolioContainersBackEnd/src/Presentation/ePortfolio.API:/app:rw"
    - "/home/ianerglitch/Documents/ePortfolioContainers/ePortfolioContainersBackEnd:/src:rw"
    - "/home/ianerglitch/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
  identity.api:
    build:
      context: "/home/ianerglitch/Documents/ePortfolioContainers/ePortfolioContainersBackEnd"
      dockerfile: "src/Presentation/Identity.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Identity.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "eidentityapi:dev"
    ports: []
    volumes:
    - "/home/ianerglitch/Documents/ePortfolioContainers/ePortfolioContainersBackEnd/src/Presentation/Identity.API:/app:rw"
    - "/home/ianerglitch/Documents/ePortfolioContainers/ePortfolioContainersBackEnd:/src:rw"
    - "/home/ianerglitch/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
